import type { Metadata } from "next";
import { LegalPageLayout, LegalSection } from "@/components/layout/LegalPageLayout";

export const metadata: Metadata = { title: "Security — AI Project Command Center" };

export default function SecurityPage() {
  return (
    <LegalPageLayout title="Security" updated="September 5, 2026">
      <p>
        This page describes the security practices actually implemented in this application today.
        It is a description of engineering choices, not a compliance certificate: this project has
        not undergone a SOC 2 Type II audit, an ISO/IEC 27001 certification, or any third-party
        security assessment. Anyone evaluating this system for a real compliance-gated procurement
        should treat every claim below as a starting point for their own audit, not a substitute
        for one.
      </p>

      <LegalSection heading="Authentication">
        <p>
          Real accounts authenticate with a bcrypt-hashed password and a signed JSON Web Token
          (HS256). Anonymous demo visitors receive a separate, short-lived (120-minute), read-only
          token scoped to a seeded demo organization — a demo session can never write data, and is
          cryptographically distinguishable from a real authenticated session at every layer of the
          backend.
        </p>
      </LegalSection>

      <LegalSection heading="Authorization">
        <p>
          Every request carries an organization id derived from its token, never from client input.
          Every domain table and query is scoped to that organization — there is no code path that
          reads across tenants. Mutating endpoints additionally check a role-based permission grant
          stored in the database (not a hardcoded if/else), so access decisions are auditable data,
          not buried logic.
        </p>
      </LegalSection>

      <LegalSection heading="Data in transit and at rest">
        <p>
          All traffic is served over TLS. The frontend and backend communicate through a same-origin
          reverse proxy, so a browser session never makes a direct cross-origin request to the API.
          The database is a managed Postgres instance (Neon) with encryption at rest provided by the
          hosting provider.
        </p>
      </LegalSection>

      <LegalSection heading="Input handling">
        <p>
          Every request body is validated against a strict schema before it reaches business logic.
          Every database query goes through a parameterized ORM layer — there is no raw,
          string-interpolated SQL anywhere in this codebase, which is the primary defense against
          SQL injection.
        </p>
      </LegalSection>

      <LegalSection heading="AI and document processing">
        <p>
          Document text extraction and embedding run on a lightweight, deterministic feature-hashing
          algorithm executed entirely within this application&apos;s own backend process — no document
          content is sent to a third-party embedding API. When a live AI provider is configured, a
          document&apos;s extracted text may be sent to that provider to answer a question about it;
          in this deployment&apos;s current default configuration, AI responses are generated by a
          local, deterministic fallback rather than a live third-party model, and no API keys are
          ever exposed to the browser.
        </p>
      </LegalSection>

      <LegalSection heading="Audit trail">
        <p>
          Logins, project and task mutations, budget changes, document uploads, and AI requests are
          written to an append-only audit log with the actor, action, affected entity, and a
          server-stamped timestamp. There is no endpoint that updates or deletes an audit log entry.
        </p>
      </LegalSection>

      <LegalSection heading="Known gaps — disclosed, not hidden">
        <p>
          There is no general-purpose inbound API rate limiter beyond two purpose-built quotas (an
          AI request budget and a demo-upload budget). There is no Content-Security-Policy header
          configured yet. Both are real, scoped engineering work, not yet done — listed here rather
          than left for someone else to discover.
        </p>
      </LegalSection>

      <LegalSection heading="Reporting a concern">
        <p>
          This is a demonstration deployment. If you believe you have found a security issue,
          contact the maintainer through the repository this project is published in.
        </p>
      </LegalSection>
    </LegalPageLayout>
  );
}
