"""pmo engines: raci stage gates contract ledger

Revision ID: 131a14753166
Revises: 679c60d91b99
Create Date: 2026-09-02 07:56:08.758668

New tables backing the Advanced PMO engines (app/models/pmo.py): raci_entries, stage_gates,
contract_ledger. EVM and the boardroom memo have no tables of their own — computed on every
read/generate by app/services/evm.py and app/services/boardroom_memo.py respectively.

(Note: alembic autogenerate also proposed dropping 'permissions_key_key' — that's the same
pre-existing metadata noise from the Phase 5 migration already called out in
679c60d91b99_email_globally_unique.py, unrelated to this change, so it's deliberately left out.)
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '131a14753166'
down_revision: Union[str, None] = '679c60d91b99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contract_ledger',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('total_contract_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('billed_to_date', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('wip', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contract_ledger_project_id'), 'contract_ledger', ['project_id'], unique=True)
    op.create_table('raci_entries',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('task_or_deliverable', sa.String(length=255), nullable=False),
    sa.Column('responsible_id', sa.UUID(), nullable=True),
    sa.Column('accountable_id', sa.UUID(), nullable=True),
    sa.Column('consulted_id', sa.UUID(), nullable=True),
    sa.Column('informed_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accountable_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['consulted_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['informed_id'], ['resources.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['responsible_id'], ['resources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raci_entries_project_id'), 'raci_entries', ['project_id'], unique=False)
    op.create_table('stage_gates',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('gate', sa.Enum('G1', 'G2', 'G3', 'G4', 'G5', name='stage_gate_number'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_REVIEW', 'APPROVED', 'REJECTED', name='stage_gate_status'), nullable=False),
    sa.Column('approver', sa.String(length=255), nullable=True),
    sa.Column('signed_off_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'gate', name='uq_stage_gates_project_gate')
    )
    op.create_index(op.f('ix_stage_gates_project_id'), 'stage_gates', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_gates_project_id'), table_name='stage_gates')
    op.drop_table('stage_gates')
    op.drop_index(op.f('ix_raci_entries_project_id'), table_name='raci_entries')
    op.drop_table('raci_entries')
    op.drop_index(op.f('ix_contract_ledger_project_id'), table_name='contract_ledger')
    op.drop_table('contract_ledger')
    # ### end Alembic commands ###
